#!/bin/bash
# Created by SharkPlush on GitHub
# https://github.com/SharkPlush
# Licensed under CC BY-NC 4.0.
set -euo pipefail
logic () {
    if [[ $(< /sys/class/dmi/id/chassis_type) =~ ^(8|9|10|11|14|31|32)$ ]]; then # WE NEED TO DETECT THE DEVICE TYPE TO AVOID FALSE POSITIVES
      echo "Detected a mobile device"
      
      LINE_POWER_PATH=$(upower -e | grep -E 'line_power') # WE FIND THE LINE_POWER PATH
      if [[ -z $LINE_POWER_PATH ]]; then
        # IF THE PATH IS MISSING UPDATE WITH WARNINGS AND AC STATUS WILL BE UNDETECTABLE
        echo "Can't find the line power path so AC status is undetermined, running update in 30 seconds but something might be wrong.."
        sleep 30
        transactional-update cleanup ${UPDATE_METHOD} reboot
      fi
      
      if [[ $(upower -i "$LINE_POWER_PATH" | awk '/online:/ {print $2}') == "yes" ]]; then
        echo "Device is plugged in, starting update in 30 seconds.." # IF THE DEVICE IS PLUGGED IN WE UPDATE
        sleep 30
        transactional-update cleanup ${UPDATE_METHOD} reboot
      
      elif [[ $(upower -i "$LINE_POWER_PATH" | awk '/online:/ {print $2}') == "no" ]]; then
        echo "Device is unplugged waiting for AC power.." # IF THE DEVICE IS UNPLUGGED WE "wait_ac"
        wait_ac
      fi  
    
    else
      echo "Device isn't a mobile device, starting update in 30 seconds.." # IF THE DEVICE TYPE IS A PC WE JUST UPDATE
      sleep 30
      transactional-update cleanup ${UPDATE_METHOD} reboot
    fi
}
  
wait_ac () {
  if [[ $(busctl wait org.freedesktop.UPower $LINE_POWER_PATH org.freedesktop.DBus.Properties PropertiesChanged | grep -m1 -oE "true") == "true" ]]; then
    echo "Device is plugged in, starting update in 30 seconds.."
    sleep 30
    transactional-update cleanup ${UPDATE_METHOD} reboot
  else
    echo "The AC state was unexpected, exiting.."
    exit 1
  fi
}
logic
